### ISSUE TITLE
LMDB Embeddings

### ISSUE THREAD

**Issue by DomHudson** [kermitt2/delft#10]
Hi, thanks for the good work!

Loving the idea of using LMDB to store and query the embeddings! I wrote a standalone package for this here: https://github.com/ThoughtRiver/lmdb-embeddings/tree/master. I thought it could be of use to embed it here thereby separating the logic out, but also to use in other settings. Is it worth me doing some work on this?

Let me know what you think!
Thanks

**Comment by kermitt2** [comment]
Hi Dom,

Thanks for the feedback! 

I also thought at some point about an independent library for the embedding management with LMDB, because it could work on any python DL frameworks, so possibly useful for many! 
 
I guess it depends on how much logic we want to put in the independent package. If we want to manage embeddings, we would maybe need some extra attributes which can be set at reading time, like the number of dimensions... We might want also an iterator for all the entries in the embeddings. 

Your package is very generic and capture only the required minimum, so I think it would be easy to integrate it in DeLFT - this would simplify my class Embeddings.py (which is too heavy). I will look at it this week-end and give you more feedback. 

One question, did you get some: 

> mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot

when opening a transaction? For me, this was extremely rare, but I needed in this case to close and reopen the environment when catching this exception.

**Comment by DomHudson** [comment]
I have got this error now! I fixed it by avoiding locking during read transactions. As our use of embeddings is strictly segmented between reading and writing, just moving to `lock=False` for all read transactions prevented the error.

**Comment by de-code** [comment]
Would it make sense to move the LMDB db creation out as well? (it doesn't seem to be part of the project)

I've added some [functionality to automatically download embeddings](https://github.com/elifesciences/sciencebeam-trainer-delft/blob/develop/sciencebeam_trainer_delft/embedding/manager.py) which seems like it could be part of a more generic library.

**Comment by de-code** [comment]
There may be an issue with the license, as [lmdb-embeddings](https://github.com/ThoughtRiver/lmdb-embeddings) is currently licensed under GPL rather than a MIT compatible license.

**Comment by kermitt2** [comment]
Indeed license not compatible!

**Comment by DomHudson** [comment]
Ah okay. I can't change the license so we'll have to park for now unfortunately
