### ISSUE TITLE
Using delft as a library

### ISSUE THREAD

**Issue by de-code** [kermitt2/delft#36]
It would be good to be able to use and install delft as a library. You could then also push it to pypi.
Some changes would be required of course.

It could maybe work a bit like this:

```bash
pip install delft==1.0.0
# or pip install delft[gpu]==1.0.0

python -m delft.download_embedding glove-840B

python -m delft.grobid_tagger --embedding glove-840B --input ... --output ...
```

What are your thoughts on that, @kermitt2?

**Comment by kermitt2** [comment]
DeLFT is already packaged as a library and pushed to pypi, https://pypi.org/project/delft/0.2.3/ or do I miss something? 

About the automatic downloading of embeddings, this is something to add since quite a long time for sure to have something usable "out-of-the-box", but I was not sure how to do it and which default storage to use - given that these embeddings are often already downloaded and it's a pain to have several versions of the same embeddings on the disk given their size. 
I was also thinking about donwloading the lmdb data files rather than the embeddings.

**Comment by de-code** [comment]
Alright, didn't realise that. There is nothing in the README I believe.

The delft package is there. But the programs like `grobidTagger` are missing. I think it would be good if they would be included. i.e. one could do everything with the package unless code changes are required.

**Comment by kermitt2** [comment]
Well there's the pypi badge in the readme :)
and the `setup.py` file 

The scripts like `grobidTagger` are actually examples of usage of the library. For including them, it would suppose to reorganise a bit all these "usage" files in a dedicated subdirectory.
